<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>Heta language</string>
    <key>scopeName</key>
    <string>source.heta</string>
    <key>fileTypes</key>
    <array>
      <string>heta</string>
    </array>
    <key>limitLineLength</key>
    <false/>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#linecomment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#blockcomment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#note</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#includeStatement</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#namespace</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#basestruct</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>unknown</key>
      <dict>
        <key>name</key>
        <string>invalid.illegal.heta</string>
        <key>match</key>
        <string>.+</string>
      </dict>
      <key>index</key>
      <dict>
        <key>name</key>
        <string>meta.index.heta</string>
        <key>match</key>
        <string>(?:([A-Za-z_]\w*)::)?([A-Za-z_]\w*)</string>
        <key>captures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.id.heta</string>
          </dict>
        </dict>
      </dict>
      <key>assignmentConst</key>
      <dict>
        <key>name</key>
        <string>meta.assignment.heta</string>
        <key>match</key>
        <string>(=)\s*([-+]?[0-9]+[.]?[0-9]*([eE][-+]?[0-9]+)?)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.short.heta</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.heta</string>
          </dict>
        </dict>
      </dict>
      <key>assignment</key>
      <dict>
        <key>name</key>
        <string>meta.assignment.heta</string>
        <key>begin</key>
        <string>([.:]=)|(\[(\w*)\]=)</string>
        <key>end</key>
        <string>(?=[;{@#'])</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.short.heta</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>id.heta</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>[^;{@#']*</string>
            <key>name</key>
            <string>string.other.expression.heta</string>
          </dict>
        </array>
      </dict>
      <key>includeStatement</key>
      <dict>
        <key>name</key>
        <string>meta.include.heta</string>
        <key>match</key>
        <string>(include)\s+("?[\w./\-]+"?)(?:\s+(type)\s+("?\w+"?))?(?:\s+(with)\s+(.+))?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.reserved.heta</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.other.heta</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.reserved.heta</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>string.other.heta</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>keyword.control.reserved.heta</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>entity.other.heta</string>
          </dict>
        </dict>
      </dict>
      <key>namespace</key>
      <dict>
        <key>name</key>
        <string>meta.namespace.heta</string>
        <key>begin</key>
        <string>(\b(abstract|concrete)\b)?\s*\b(namespace)\b\s+(.*)\s+(begin)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.reserved.heta</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.reserved.heta</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>keyword.control.begin.heta</string>
          </dict>
        </dict>
        <key>end</key>
        <string>end</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.end.heta</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#linecomment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#blockcomment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#includeStatement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#note</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#basestruct</string>
          </dict>
        </array>
      </dict>
      <key>basestruct</key>
      <dict>
        <key>name</key>
        <string>meta.basestruct.heta</string>
        <key>end</key>
        <string>;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#index</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#linecomment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#blockcomment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#class</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#action</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#title</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dict</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#assignmentConst</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#assignment</string>
          </dict>
        </array>
      </dict>
      <key>dict</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>dictionary.begin.heta</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>dictionary.end.heta</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.dictionary.heta</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#linecomment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#blockcomment</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.other.heta</string>
            <key>begin</key>
            <string>([A-Za-z_][A-Za-z0-9_]*)\s*:\s*</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.key.heta</string>
              </dict>
            </dict>
            <key>end</key>
            <string>,|(?=//)|(?=/\*)|(?=})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#dict</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#array</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#boolean</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#number</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>number</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.heta</string>
        <key>match</key>
        <string>[-+]?[0-9]+[.]?[0-9]*([eE][-+]?[0-9]+)?\b</string>
      </dict>
      <key>boolean</key>
      <dict>
        <key>name</key>
        <string>constant.language.heta</string>
        <key>match</key>
        <string>(true)|(false)</string>
      </dict>
      <key>string</key>
      <dict>
        <key>name</key>
        <string>string.other.heta</string>
        <key>match</key>
        <string>".*?"|[^"]*?(?=(//|/\*|,|}|]|$))</string>
      </dict>
      <key>array</key>
      <dict>
        <key>name</key>
        <string>meta.array.heta</string>
        <key>begin</key>
        <string>\[</string>
        <key>end</key>
        <string>\]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#linecomment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#blockcomment</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s+</string>
          </dict>
          <dict>
            <key>begin</key>
            <string></string>
            <key>end</key>
            <string>,|(?=//)|(?=/\*)|(?=\])</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>array.end.heta</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#dict</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#array</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#boolean</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#number</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>note</key>
      <dict>
        <key>name</key>
        <string>comment.block.documentation.note.heta</string>
        <key>begin</key>
        <string>'''</string>
        <key>end</key>
        <string>'''</string>
      </dict>
      <key>class</key>
      <dict>
        <key>name</key>
        <string>support.class.heta</string>
        <key>match</key>
        <string>@\w+</string>
      </dict>
      <key>title</key>
      <dict>
        <key>name</key>
        <string>string.quoted.heta</string>
        <key>match</key>
        <string>'.*?'</string>
      </dict>
      <key>linecomment</key>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.heta</string>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>$</string>
      </dict>
      <key>blockcomment</key>
      <dict>
        <key>name</key>
        <string>comment.block.heta</string>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
      </dict>
      <key>action</key>
      <dict>
        <key>name</key>
        <string>support.function.action.heta</string>
        <key>match</key>
        <string>#\w+</string>
      </dict>
    </dict>
  </dict>
</plist>